version: '2'

services:
  codeship_example:
    ui-tests:
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - ./tests/report/:/home/uitests/public_app_ui/gen/
        - ./tests/logs/:/home/uitests/public_app_ui/build/
        - ./build/allure-report/:/home/uitests/public_app_ui/allure-report/
      command: sleep infinity